from typing import Callable, List, Optional, Type, Union

from gi.repository import Gio, GLib, GObject

MAJOR_VERSION: int
MINOR_VERSION: int
MICRO_VERSION: int
VERSION: str

def get_default() -> 'Hyprland': ...

class Fullscreen(GObject.GFlags):
    CURRENT = -1
    NONE = 0
    MAXIMIZED = 1
    FULLSCREEN = 2

class MonitorTransform(GObject.GEnum):
    NORMAL = 0
    ROTATE_90_DEG = 1
    ROTATE_180_DEG = 2
    ROTATE_270_DEG = 3
    FLIPPED = 4
    FLIPPED_ROTATE_90_DEG = 5
    FLIPPED_ROTATE_180_DEG = 6
    FLIPPED_ROTATE_270_DEG = 7

class Client(GObject.Object):
    """
    :property address: (str)
    :property mapped: (bool)
    :property hidden: (bool)
    :property x: (int)
    :property y: (int)
    :property width: (int)
    :property height: (int)
    :property workspace: (Workspace)
    :property floating: (bool)
    :property monitor: (Monitor)
    :property class_: (str) - Note: accessing property via 'class' matches C, but in python use get_class() or props.class_
    :property title: (str)
    :property initial_class: (str)
    :property initial_title: (str)
    :property pid: (int)
    :property xwayland: (bool)
    :property pinned: (bool)
    :property fullscreen: (Fullscreen)
    :property fullscreen_client: (Fullscreen)
    :property swallowing: (str)
    :property focus_history_id: (int)
    """

    @property
    def address(self) -> str: ...
    @address.setter
    def address(self, value: str): ...
    @property
    def mapped(self) -> bool: ...
    @mapped.setter
    def mapped(self, value: bool): ...
    @property
    def hidden(self) -> bool: ...
    @hidden.setter
    def hidden(self, value: bool): ...
    @property
    def x(self) -> int: ...
    @x.setter
    def x(self, value: int): ...
    @property
    def y(self) -> int: ...
    @y.setter
    def y(self, value: int): ...
    @property
    def width(self) -> int: ...
    @width.setter
    def width(self, value: int): ...
    @property
    def height(self) -> int: ...
    @height.setter
    def height(self, value: int): ...
    @property
    def workspace(self) -> 'Workspace': ...
    @workspace.setter
    def workspace(self, value: 'Workspace'): ...
    @property
    def floating(self) -> bool: ...
    @floating.setter
    def floating(self, value: bool): ...
    @property
    def monitor(self) -> 'Monitor': ...
    @monitor.setter
    def monitor(self, value: 'Monitor'): ...

    # "class" is a reserved keyword in Python, usually accessed via props or renamed
    @property
    def class_(self) -> str: ...
    @class_.setter
    def class_(self, value: str): ...
    @property
    def title(self) -> str: ...
    @title.setter
    def title(self, value: str): ...
    @property
    def initial_class(self) -> str: ...
    @initial_class.setter
    def initial_class(self, value: str): ...
    @property
    def initial_title(self) -> str: ...
    @initial_title.setter
    def initial_title(self, value: str): ...
    @property
    def pid(self) -> int: ...
    @pid.setter
    def pid(self, value: int): ...
    @property
    def xwayland(self) -> bool: ...
    @xwayland.setter
    def xwayland(self, value: bool): ...
    @property
    def pinned(self) -> bool: ...
    @pinned.setter
    def pinned(self, value: bool): ...
    @property
    def fullscreen(self) -> Fullscreen: ...
    @fullscreen.setter
    def fullscreen(self, value: Fullscreen): ...
    @property
    def fullscreen_client(self) -> Fullscreen: ...
    @fullscreen_client.setter
    def fullscreen_client(self, value: Fullscreen): ...
    @property
    def swallowing(self) -> str: ...
    @swallowing.setter
    def swallowing(self, value: str): ...
    @property
    def focus_history_id(self) -> int: ...
    @focus_history_id.setter
    def focus_history_id(self, value: int): ...
    def __init__(self, **kwargs): ...
    @classmethod
    def new(cls) -> 'Client': ...
    def kill(self) -> None: ...
    def focus(self) -> None: ...
    def move_to(self, ws: 'Workspace') -> None: ...
    def toggle_floating(self) -> None: ...
    def get_address(self) -> str: ...
    def get_mapped(self) -> bool: ...
    def get_hidden(self) -> bool: ...
    def get_x(self) -> int: ...
    def get_y(self) -> int: ...
    def get_width(self) -> int: ...
    def get_height(self) -> int: ...
    def get_workspace(self) -> 'Workspace': ...
    def get_floating(self) -> bool: ...
    def get_monitor(self) -> 'Monitor': ...
    def get_class(self) -> str: ...
    def get_title(self) -> str: ...
    def get_initial_class(self) -> str: ...
    def get_initial_title(self) -> str: ...
    def get_pid(self) -> int: ...
    def get_xwayland(self) -> bool: ...
    def get_pinned(self) -> bool: ...
    def get_fullscreen(self) -> Fullscreen: ...
    def get_fullscreen_client(self) -> Fullscreen: ...
    def get_swallowing(self) -> str: ...
    def get_focus_history_id(self) -> int: ...

class Monitor(GObject.Object):
    """
    :property id: (int)
    :property name: (str)
    :property description: (str)
    :property make: (str)
    :property model: (str)
    :property serial: (str)
    :property width: (int)
    :property height: (int)
    :property refresh_rate: (float)
    :property x: (int)
    :property y: (int)
    :property active_workspace: (Workspace)
    :property special_workspace: (Workspace)
    :property reserved_top: (int)
    :property reserved_bottom: (int)
    :property reserved_left: (int)
    :property reserved_right: (int)
    :property scale: (float)
    :property transform: (MonitorTransform)
    :property focused: (bool)
    :property dpms_status: (bool)
    :property vrr: (bool)
    :property actively_tearing: (bool)
    :property disabled: (bool)
    :property current_format: (str)
    :property available_modes: (List[str])
    """

    @property
    def id(self) -> int: ...
    @id.setter
    def id(self, value: int): ...
    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, value: str): ...
    @property
    def description(self) -> str: ...
    @description.setter
    def description(self, value: str): ...
    @property
    def make(self) -> str: ...
    @make.setter
    def make(self, value: str): ...
    @property
    def model(self) -> str: ...
    @model.setter
    def model(self, value: str): ...
    @property
    def serial(self) -> str: ...
    @serial.setter
    def serial(self, value: str): ...
    @property
    def width(self) -> int: ...
    @width.setter
    def width(self, value: int): ...
    @property
    def height(self) -> int: ...
    @height.setter
    def height(self, value: int): ...
    @property
    def refresh_rate(self) -> float: ...
    @refresh_rate.setter
    def refresh_rate(self, value: float): ...
    @property
    def x(self) -> int: ...
    @x.setter
    def x(self, value: int): ...
    @property
    def y(self) -> int: ...
    @y.setter
    def y(self, value: int): ...
    @property
    def active_workspace(self) -> 'Workspace': ...
    @active_workspace.setter
    def active_workspace(self, value: 'Workspace'): ...
    @property
    def special_workspace(self) -> 'Workspace': ...
    @special_workspace.setter
    def special_workspace(self, value: 'Workspace'): ...
    @property
    def reserved_top(self) -> int: ...
    @reserved_top.setter
    def reserved_top(self, value: int): ...
    @property
    def reserved_bottom(self) -> int: ...
    @reserved_bottom.setter
    def reserved_bottom(self, value: int): ...
    @property
    def reserved_left(self) -> int: ...
    @reserved_left.setter
    def reserved_left(self, value: int): ...
    @property
    def reserved_right(self) -> int: ...
    @reserved_right.setter
    def reserved_right(self, value: int): ...
    @property
    def scale(self) -> float: ...
    @scale.setter
    def scale(self, value: float): ...
    @property
    def transform(self) -> MonitorTransform: ...
    @transform.setter
    def transform(self, value: MonitorTransform): ...
    @property
    def focused(self) -> bool: ...
    @focused.setter
    def focused(self, value: bool): ...
    @property
    def dpms_status(self) -> bool: ...
    @dpms_status.setter
    def dpms_status(self, value: bool): ...
    @property
    def vrr(self) -> bool: ...
    @vrr.setter
    def vrr(self, value: bool): ...
    @property
    def actively_tearing(self) -> bool: ...
    @actively_tearing.setter
    def actively_tearing(self, value: bool): ...
    @property
    def disabled(self) -> bool: ...
    @disabled.setter
    def disabled(self, value: bool): ...
    @property
    def current_format(self) -> str: ...
    @current_format.setter
    def current_format(self, value: str): ...
    @property
    def available_modes(self) -> List[str]: ...
    @available_modes.setter
    def available_modes(self, value: List[str]): ...
    def __init__(self, **kwargs): ...
    @classmethod
    def new(cls) -> 'Monitor': ...
    def focus(self) -> None: ...
    def get_id(self) -> int: ...
    def get_name(self) -> str: ...
    def get_description(self) -> str: ...
    def get_make(self) -> str: ...
    def get_model(self) -> str: ...
    def get_serial(self) -> str: ...
    def get_width(self) -> int: ...
    def get_height(self) -> int: ...
    def get_refresh_rate(self) -> float: ...
    def get_x(self) -> int: ...
    def get_y(self) -> int: ...
    def get_active_workspace(self) -> 'Workspace': ...
    def get_special_workspace(self) -> 'Workspace': ...
    def get_reserved_top(self) -> int: ...
    def get_reserved_bottom(self) -> int: ...
    def get_reserved_left(self) -> int: ...
    def get_reserved_right(self) -> int: ...
    def get_scale(self) -> float: ...
    def get_transform(self) -> MonitorTransform: ...
    def get_focused(self) -> bool: ...
    def get_dpms_status(self) -> bool: ...
    def get_vrr(self) -> bool: ...
    def get_actively_tearing(self) -> bool: ...
    def get_disabled(self) -> bool: ...
    def get_current_format(self) -> str: ...
    def get_available_modes(self) -> List[str]: ...

class Workspace(GObject.Object):
    """
    :property id: (int)
    :property name: (str)
    :property monitor: (Monitor)
    :property clients: (List[Client])
    :property has_fullscreen: (bool)
    :property last_client: (Client)
    """

    @property
    def id(self) -> int: ...
    @id.setter
    def id(self, value: int): ...
    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, value: str): ...
    @property
    def monitor(self) -> 'Monitor': ...
    @monitor.setter
    def monitor(self, value: 'Monitor'): ...
    @property
    def clients(self) -> List[Client]: ...
    @property
    def has_fullscreen(self) -> bool: ...
    @has_fullscreen.setter
    def has_fullscreen(self, value: bool): ...
    @property
    def last_client(self) -> Client: ...
    @last_client.setter
    def last_client(self, value: Client): ...
    def __init__(self, **kwargs): ...
    @classmethod
    def new(cls) -> 'Workspace': ...
    @classmethod
    def dummy(cls, id: int, monitor: Optional[Monitor] = None) -> 'Workspace': ...
    def focus(self) -> None: ...
    def move_to(self, m: Monitor) -> None: ...
    def get_id(self) -> int: ...
    def get_name(self) -> str: ...
    def get_monitor(self) -> Monitor: ...
    def get_clients(self) -> List[Client]: ...
    def get_has_fullscreen(self) -> bool: ...
    def get_last_client(self) -> Client: ...

class Bind(GObject.Object):
    """
    :property locked: (bool)
    :property mouse: (bool)
    :property release: (bool)
    :property repeat: (bool)
    :property long_press: (bool)
    :property non_consuming: (bool)
    :property has_description: (bool)
    :property modmask: (int)
    :property submap: (str)
    :property key: (str)
    :property keycode: (int)
    :property catch_all: (bool)
    :property description: (str)
    :property dispatcher: (str)
    :property arg: (str)
    """

    @property
    def locked(self) -> bool: ...
    @locked.setter
    def locked(self, value: bool): ...
    @property
    def mouse(self) -> bool: ...
    @mouse.setter
    def mouse(self, value: bool): ...
    @property
    def release(self) -> bool: ...
    @release.setter
    def release(self, value: bool): ...
    @property
    def repeat(self) -> bool: ...
    @repeat.setter
    def repeat(self, value: bool): ...
    @property
    def long_press(self) -> bool: ...
    @long_press.setter
    def long_press(self, value: bool): ...
    @property
    def non_consuming(self) -> bool: ...
    @non_consuming.setter
    def non_consuming(self, value: bool): ...
    @property
    def has_description(self) -> bool: ...
    @has_description.setter
    def has_description(self, value: bool): ...
    @property
    def modmask(self) -> int: ...
    @modmask.setter
    def modmask(self, value: int): ...
    @property
    def submap(self) -> str: ...
    @submap.setter
    def submap(self, value: str): ...
    @property
    def key(self) -> str: ...
    @key.setter
    def key(self, value: str): ...
    @property
    def keycode(self) -> int: ...
    @keycode.setter
    def keycode(self, value: int): ...
    @property
    def catch_all(self) -> bool: ...
    @catch_all.setter
    def catch_all(self, value: bool): ...
    @property
    def description(self) -> str: ...
    @description.setter
    def description(self, value: str): ...
    @property
    def dispatcher(self) -> str: ...
    @dispatcher.setter
    def dispatcher(self, value: str): ...
    @property
    def arg(self) -> str: ...
    @arg.setter
    def arg(self, value: str): ...
    def __init__(self, **kwargs): ...
    @classmethod
    def new(cls) -> 'Bind': ...
    def get_locked(self) -> bool: ...
    def set_locked(self, value: bool) -> None: ...
    def get_mouse(self) -> bool: ...
    def set_mouse(self, value: bool) -> None: ...
    def get_release(self) -> bool: ...
    def set_release(self, value: bool) -> None: ...
    def get_repeat(self) -> bool: ...
    def set_repeat(self, value: bool) -> None: ...
    def get_long_press(self) -> bool: ...
    def set_long_press(self, value: bool) -> None: ...
    def get_non_consuming(self) -> bool: ...
    def set_non_consuming(self, value: bool) -> None: ...
    def get_has_description(self) -> bool: ...
    def set_has_description(self, value: bool) -> None: ...
    def get_modmask(self) -> int: ...
    def set_modmask(self, value: int) -> None: ...
    def get_submap(self) -> str: ...
    def set_submap(self, value: str) -> None: ...
    def get_key(self) -> str: ...
    def set_key(self, value: str) -> None: ...
    def get_keycode(self) -> int: ...
    def set_keycode(self, value: int) -> None: ...
    def get_catch_all(self) -> bool: ...
    def set_catch_all(self, value: bool) -> None: ...
    def get_description(self) -> str: ...
    def set_description(self, value: str) -> None: ...
    def get_dispatcher(self) -> str: ...
    def set_dispatcher(self, value: str) -> None: ...
    def get_arg(self) -> str: ...
    def set_arg(self, value: str) -> None: ...

class Position(GObject.Object):
    """
    :property x: (int)
    :property y: (int)
    """

    @property
    def x(self) -> int: ...
    @x.setter
    def x(self, value: int): ...
    @property
    def y(self) -> int: ...
    @y.setter
    def y(self, value: int): ...
    def __init__(self, **kwargs): ...
    @classmethod
    def new(cls) -> 'Position': ...
    def get_x(self) -> int: ...
    def set_x(self, value: int) -> None: ...
    def get_y(self) -> int: ...
    def set_y(self, value: int) -> None: ...

class Hyprland(GObject.Object):
    """
    :property monitors: (List[Monitor])
    :property workspaces: (List[Workspace])
    :property clients: (List[Client])
    :property focused_workspace: (Workspace)
    :property focused_monitor: (Monitor)
    :property focused_client: (Client)
    :property binds: (List[Bind])
    :property cursor_position: (Position)
    """

    @property
    def monitors(self) -> List[Monitor]: ...
    @property
    def workspaces(self) -> List[Workspace]: ...
    @property
    def clients(self) -> List[Client]: ...
    @property
    def focused_workspace(self) -> Workspace: ...
    @focused_workspace.setter
    def focused_workspace(self, value: Workspace): ...
    @property
    def focused_monitor(self) -> Monitor: ...
    @focused_monitor.setter
    def focused_monitor(self, value: Monitor): ...
    @property
    def focused_client(self) -> Client: ...
    @focused_client.setter
    def focused_client(self, value: Client): ...
    @property
    def binds(self) -> List[Bind]: ...
    @property
    def cursor_position(self) -> Position: ...
    def __init__(self, **kwargs): ...
    @classmethod
    def new(cls) -> 'Hyprland': ...
    @staticmethod
    def get_default() -> Optional['Hyprland']: ...
    def get_monitor(self, id: int) -> Monitor: ...
    def get_workspace(self, id: int) -> Workspace: ...
    def get_client(self, address: str) -> Optional[Client]: ...
    def get_monitor_by_name(self, name: str) -> Optional[Monitor]: ...
    def get_workspace_by_name(self, name: str) -> Optional[Workspace]: ...
    def message(self, message: str) -> str: ...
    def message_async(
        self, message: str, callback: Optional[Callable] = None, *args
    ) -> None: ...
    def message_finish(self, res: Gio.AsyncResult) -> str: ...
    def dispatch(self, dispatcher: str, args: str) -> None: ...
    def move_cursor(self, x: int, y: int) -> None: ...
    def sync_monitors(self, callback: Optional[Callable] = None, *args) -> None: ...
    def sync_monitors_finish(self, res: Gio.AsyncResult) -> None: ...
    def sync_workspaces(self, callback: Optional[Callable] = None, *args) -> None: ...
    def sync_workspaces_finish(self, res: Gio.AsyncResult) -> None: ...
    def sync_clients(self, callback: Optional[Callable] = None, *args) -> None: ...
    def sync_clients_finish(self, res: Gio.AsyncResult) -> None: ...
    def get_monitors(self) -> List[Monitor]: ...
    def get_workspaces(self) -> List[Workspace]: ...
    def get_clients(self) -> List[Client]: ...
    def get_focused_workspace(self) -> Workspace: ...
    def get_focused_monitor(self) -> Monitor: ...
    def get_focused_client(self) -> Client: ...
    def get_binds(self) -> List[Bind]: ...
    def get_cursor_position(self) -> Position: ...
