import typing
from typing import Any, Callable, List, Optional

from gi.repository import Gio, GLib, GObject

# Constants
MAJOR_VERSION: int
MINOR_VERSION: int
MICRO_VERSION: int
VERSION: str

def get_default() -> 'Bluetooth': ...

class Adapter(GObject.Object):

    # Properties
    @property
    def uuids(self) -> List[str]: ...
    @property
    def discovering(self) -> bool: ...
    @property
    def modalias(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def class_(self) -> int: ...
    @property
    def address(self) -> str: ...
    @property
    def discoverable(self) -> bool: ...
    @discoverable.setter
    def discoverable(self, value: bool): ...
    @property
    def pairable(self) -> bool: ...
    @pairable.setter
    def pairable(self, value: bool): ...
    @property
    def powered(self) -> bool: ...
    @powered.setter
    def powered(self, value: bool): ...
    @property
    def alias(self) -> str: ...
    @alias.setter
    def alias(self, value: str): ...
    @property
    def discoverable_timeout(self) -> int: ...
    @discoverable_timeout.setter
    def discoverable_timeout(self, value: int): ...
    @property
    def pairable_timeout(self) -> int: ...
    @pairable_timeout.setter
    def pairable_timeout(self, value: int): ...

    # Methods
    def remove_device(self, device: 'Device') -> None: ...
    def start_discovery(self) -> None: ...
    def stop_discovery(self) -> None: ...
    def get_uuids(self) -> List[str]: ...
    def get_discovering(self) -> bool: ...
    def get_modalias(self) -> str: ...
    def get_name(self) -> str: ...
    def get_class(self) -> int: ...
    def get_address(self) -> str: ...
    def get_discoverable(self) -> bool: ...
    def set_discoverable(self, value: bool) -> None: ...
    def get_pairable(self) -> bool: ...
    def set_pairable(self, value: bool) -> None: ...
    def get_powered(self) -> bool: ...
    def set_powered(self, value: bool) -> None: ...
    def get_alias(self) -> str: ...
    def set_alias(self, value: str) -> None: ...
    def get_discoverable_timeout(self) -> int: ...
    def set_discoverable_timeout(self, value: int) -> None: ...
    def get_pairable_timeout(self) -> int: ...
    def set_pairable_timeout(self, value: int) -> None: ...

class Bluetooth(GObject.Object):
    """
    Manager object for `org.bluez`.
    """

    @staticmethod
    def get_default() -> 'Bluetooth': ...
    @staticmethod
    def new() -> 'Bluetooth': ...

    # Properties
    @property
    def is_powered(self) -> bool: ...
    @is_powered.setter
    def is_powered(self, value: bool): ...
    @property
    def is_connected(self) -> bool: ...
    @is_connected.setter
    def is_connected(self, value: bool): ...
    @property
    def adapter(self) -> Optional[Adapter]: ...
    @property
    def adapters(self) -> List[Adapter]: ...
    @property
    def devices(self) -> List['Device']: ...

    # Methods
    def toggle(self) -> None: ...
    def get_is_powered(self) -> bool: ...
    def get_is_connected(self) -> bool: ...
    def get_adapter(self) -> Optional[Adapter]: ...
    def get_adapters(self) -> List[Adapter]: ...
    def get_devices(self) -> List['Device']: ...

    # Signals
    def connect(self, signal: str, callback: Callable[..., Any], *args: Any) -> int: ...
    # Signal signatures:
    # "device-added": (self, device: Device)
    # "device-removed": (self, device: Device)
    # "adapter-added": (self, adapter: Adapter)
    # "adapter-removed": (self, adapter: Adapter)

class Device(GObject.Object):
    """
    Object representing a [device](https://github.com/luetzel/bluez/blob/master/doc/device-api.txt).
    """

    # Properties
    @property
    def uuids(self) -> List[str]: ...
    @property
    def connected(self) -> bool: ...
    @property
    def legacy_pairing(self) -> bool: ...
    @property
    def paired(self) -> bool: ...
    @property
    def rssi(self) -> int: ...
    @property
    def adapter(self) -> str: ...  # ObjectPath
    @property
    def address(self) -> str: ...
    @property
    def icon(self) -> str: ...
    @property
    def modalias(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def appearance(self) -> int: ...
    @property
    def class_(self) -> int: ...
    @property
    def connecting(self) -> bool: ...
    @connecting.setter
    def connecting(self, value: bool): ...
    @property
    def blocked(self) -> bool: ...
    @blocked.setter
    def blocked(self, value: bool): ...
    @property
    def trusted(self) -> bool: ...
    @trusted.setter
    def trusted(self, value: bool): ...
    @property
    def battery_percentage(self) -> float: ...
    @property
    def alias(self) -> str: ...
    @alias.setter
    def alias(self, value: str): ...

    # Methods
    def connect_device(
        self,
        callback: Optional[
            Callable[[GObject.Object, Gio.AsyncResult, Any], None]
        ] = None,
        user_data: Optional[Any] = None,
    ) -> None: ...
    def connect_device_finish(self, res: Gio.AsyncResult) -> None: ...
    def disconnect_device(
        self,
        callback: Optional[
            Callable[[GObject.Object, Gio.AsyncResult, Any], None]
        ] = None,
        user_data: Optional[Any] = None,
    ) -> None: ...
    def disconnect_device_finish(self, res: Gio.AsyncResult) -> None: ...
    def connect_profile(self, uuid: str) -> None: ...
    def disconnect_profile(self, uuid: str) -> None: ...
    def pair(self) -> None: ...
    def cancel_pairing(self) -> None: ...
    def get_uuids(self) -> List[str]: ...
    def get_connected(self) -> bool: ...
    def get_legacy_pairing(self) -> bool: ...
    def get_paired(self) -> bool: ...
    def get_rssi(self) -> int: ...
    def get_adapter(self) -> str: ...
    def get_address(self) -> str: ...
    def get_icon(self) -> str: ...
    def get_modalias(self) -> str: ...
    def get_name(self) -> str: ...
    def get_appearance(self) -> int: ...
    def get_class(self) -> int: ...
    def get_connecting(self) -> bool: ...
    def get_blocked(self) -> bool: ...
    def set_blocked(self, value: bool) -> None: ...
    def get_trusted(self) -> bool: ...
    def set_trusted(self, value: bool) -> None: ...
    def get_battery_percentage(self) -> float: ...
    def get_alias(self) -> str: ...
    def set_alias(self, value: str) -> None: ...
