import enum
from typing import List, Optional

from gi.repository import Gio, GLib, GObject

class Input(enum.IntEnum):
    FIFO = 0
    PORTAUDIO = 1
    PIPEWIRE = 2
    ALSA = 3
    PULSE = 4
    SNDIO = 5
    SHMEM = 8
    WINSCAP = 9

class Cava(GObject.Object):
    """
    Main Cava object for audio visualization.
    """

    # Properties
    @property
    def active(self) -> bool: ...
    @active.setter
    def active(self, value: bool): ...
    @property
    def autosens(self) -> bool: ...
    @autosens.setter
    def autosens(self, value: bool): ...
    @property
    def bars(self) -> int: ...
    @bars.setter
    def bars(self, value: int): ...
    @property
    def channels(self) -> int: ...
    @channels.setter
    def channels(self, value: int): ...
    @property
    def framerate(self) -> int: ...
    @framerate.setter
    def framerate(self, value: int): ...
    @property
    def high_cutoff(self) -> int: ...
    @high_cutoff.setter
    def high_cutoff(self, value: int): ...
    @property
    def input(self) -> Input: ...
    @input.setter
    def input(self, value: Input): ...
    @property
    def low_cutoff(self) -> int: ...
    @low_cutoff.setter
    def low_cutoff(self, value: int): ...
    @property
    def noise_reduction(self) -> float: ...
    @noise_reduction.setter
    def noise_reduction(self, value: float): ...
    @property
    def samplerate(self) -> int: ...
    @samplerate.setter
    def samplerate(self, value: int): ...
    @property
    def source(self) -> str: ...
    @source.setter
    def source(self, value: str): ...
    @property
    def stereo(self) -> bool: ...
    @stereo.setter
    def stereo(self, value: bool): ...
    @property
    def values(self) -> List[float]: ...

    # Static Methods
    @staticmethod
    def get_default() -> Optional['Cava']: ...

    # Methods
    def get_active(self) -> bool: ...
    def set_active(self, active: bool) -> None: ...
    def get_autosens(self) -> bool: ...
    def set_autosens(self, autosens: bool) -> None: ...
    def get_bars(self) -> int: ...
    def set_bars(self, bars: int) -> None: ...
    def get_channels(self) -> int: ...
    def set_channels(self, channels: int) -> None: ...
    def get_framerate(self) -> int: ...
    def set_framerate(self, framerate: int) -> None: ...
    def get_high_cutoff(self) -> int: ...
    def set_high_cutoff(self, high_cutoff: int) -> None: ...
    def get_input(self) -> Input: ...
    def set_input(self, input: Input) -> None: ...
    def get_low_cutoff(self) -> int: ...
    def set_low_cutoff(self, low_cutoff: int) -> None: ...
    def get_noise_reduction(self) -> float: ...
    def set_noise_reduction(self, noise: float) -> None: ...
    def get_samplerate(self) -> int: ...
    def set_samplerate(self, samplerate: int) -> None: ...
    def get_source(self) -> str: ...
    def set_source(self, source: str) -> None: ...
    def get_stereo(self) -> bool: ...
    def set_stereo(self, stereo: bool) -> None: ...
    def get_values(self) -> List[float]: ...

def get_default() -> Optional[Cava]: ...
