from typing import Any, Callable, List, Optional

from gi.repository import NM, Gio, GLib, GObject

# Constants from GIR
MAJOR_VERSION: int = 0
MINOR_VERSION: int = 1
MICRO_VERSION: int = 0
VERSION: str = "0.1.0"

# Global function defined in GIR
def get_default() -> 'Network': ...

# Enums (Represented as ints in Python GI)
class Primary:
    UNKNOWN: int = 0
    WIRED: int = 1
    WIFI: int = 2

class State:
    UNKNOWN: int = 0
    ASLEEP: int = 10
    DISCONNECTED: int = 20
    DISCONNECTING: int = 30
    CONNECTING: int = 40
    CONNECTED_LOCAL: int = 50
    CONNECTED_SITE: int = 60
    CONNECTED_GLOBAL: int = 70

class Connectivity:
    UNKNOWN: int = 0
    NONE: int = 1
    PORTAL: int = 2
    LIMITED: int = 3
    FULL: int = 4

class DeviceState:
    UNKNOWN: int = 0
    UNMANAGED: int = 10
    UNAVAILABLE: int = 20
    DISCONNECTED: int = 30
    PREPARE: int = 40
    CONFIG: int = 50
    NEED_AUTH: int = 60
    IP_CONFIG: int = 70
    IP_CHECK: int = 80
    SECONDARIES: int = 90
    ACTIVATED: int = 100
    DEACTIVATING: int = 110
    FAILED: int = 120

class Internet:
    CONNECTED: int = 0
    CONNECTING: int = 1
    DISCONNECTED: int = 2

# Global Namespace Functions
def primary_to_string(self: int) -> str: ...
def primary_from_connection_type(type: str) -> int: ...
def state_to_string(self: int) -> str: ...
def connectivity_to_string(self: int) -> str: ...
def device_state_to_string(self: int) -> str: ...
def internet_from_device(device: NM.Device) -> int: ...
def internet_to_string(self: int) -> str: ...

class AccessPoint(GObject.Object):
    # GIR Fields
    ap: NM.AccessPoint

    # GIR Properties
    @property
    def bandwidth(self) -> int: ...
    @property
    def bssid(self) -> str: ...
    @property
    def frequency(self) -> int: ...
    @property
    def last_seen(self) -> int: ...
    @property
    def max_bitrate(self) -> int: ...
    @property
    def strength(self) -> int: ...
    @property
    def icon_name(self) -> str: ...
    @icon_name.setter
    def icon_name(self, value: str): ...
    @property
    def mode(self) -> NM.80211Mode: ...
    @property
    def flags(self) -> NM.80211ApFlags: ...
    @property
    def rsn_flags(self) -> NM.80211ApSecurityFlags: ...
    @property
    def wpa_flags(self) -> NM.80211ApSecurityFlags: ...
    @property
    def requires_password(self) -> bool: ...
    @property
    def ssid(self) -> Optional[str]: ...

    # GIR Methods
    def get_connections(self) -> List[NM.RemoteConnection]: ...
    def get_path(self) -> str: ...
    def activate(self, password: Optional[str] = None, callback: Optional[Callable] = None, *user_data: Any) -> None: ...
    def activate_finish(self, res: Gio.AsyncResult) -> None: ...
    def get_bandwidth(self) -> int: ...
    def get_bssid(self) -> str: ...
    def get_frequency(self) -> int: ...
    def get_last_seen(self) -> int: ...
    def get_max_bitrate(self) -> int: ...
    def get_strength(self) -> int: ...
    def get_icon_name(self) -> str: ...
    def get_mode(self) -> NM.80211Mode: ...
    def get_flags(self) -> NM.80211ApFlags: ...
    def get_rsn_flags(self) -> NM.80211ApSecurityFlags: ...
    def get_wpa_flags(self) -> NM.80211ApSecurityFlags: ...
    def get_requires_password(self) -> bool: ...
    def get_ssid(self) -> Optional[str]: ...

class Wifi(GObject.Object):
    # GIR Properties
    @property
    def device(self) -> NM.DeviceWifi: ...
    @device.setter
    def device(self, value: NM.DeviceWifi): ...
    @property
    def active_connection(self) -> Optional[NM.ActiveConnection]: ...
    @active_connection.setter
    def active_connection(self, value: Optional[NM.ActiveConnection]): ...
    @property
    def active_access_point(self) -> Optional[AccessPoint]: ...
    @active_access_point.setter
    def active_access_point(self, value: Optional[AccessPoint]): ...
    @property
    def access_points(self) -> List[AccessPoint]: ...
    @property
    def enabled(self) -> bool: ...
    @enabled.setter
    def enabled(self, value: bool): ...
    @property
    def internet(self) -> int: ...
    @internet.setter
    def internet(self, value: int): ...
    @property
    def bandwidth(self) -> int: ...
    @bandwidth.setter
    def bandwidth(self, value: int): ...
    @property
    def ssid(self) -> str: ...
    @ssid.setter
    def ssid(self, value: str): ...
    @property
    def strength(self) -> int: ...
    @strength.setter
    def strength(self, value: int): ...
    @property
    def frequency(self) -> int: ...
    @frequency.setter
    def frequency(self, value: int): ...
    @property
    def state(self) -> int: ...
    @state.setter
    def state(self, value: int): ...
    @property
    def icon_name(self) -> str: ...
    @icon_name.setter
    def icon_name(self, value: str): ...
    @property
    def is_hotspot(self) -> bool: ...
    @is_hotspot.setter
    def is_hotspot(self, value: bool): ...
    @property
    def scanning(self) -> bool: ...
    @scanning.setter
    def scanning(self, value: bool): ...

    # GIR Methods
    def scan(self) -> None: ...
    def deactivate_connection(self, callback: Optional[Callable] = None, *user_data: Any) -> None: ...
    def deactivate_connection_finish(self, res: Gio.AsyncResult) -> None: ...
    def get_device(self) -> NM.DeviceWifi: ...
    def set_device(self, value: NM.DeviceWifi) -> None: ...
    def get_active_connection(self) -> Optional[NM.ActiveConnection]: ...
    def get_active_access_point(self) -> Optional[AccessPoint]: ...
    def get_access_points(self) -> List[AccessPoint]: ...
    def get_enabled(self) -> bool: ...
    def set_enabled(self, value: bool) -> None: ...
    def get_internet(self) -> int: ...
    def get_bandwidth(self) -> int: ...
    def get_ssid(self) -> str: ...
    def get_strength(self) -> int: ...
    def get_frequency(self) -> int: ...
    def get_state(self) -> int: ...
    def get_icon_name(self) -> str: ...
    def get_is_hotspot(self) -> bool: ...
    def get_scanning(self) -> bool: ...

class Wired(GObject.Object):
    # GIR Fields
    connection: NM.ActiveConnection

    # GIR Properties
    @property
    def device(self) -> NM.DeviceEthernet: ...
    @device.setter
    def device(self, value: NM.DeviceEthernet): ...
    @property
    def speed(self) -> int: ...
    @speed.setter
    def speed(self, value: int): ...
    @property
    def internet(self) -> int: ...
    @internet.setter
    def internet(self, value: int): ...
    @property
    def state(self) -> int: ...
    @state.setter
    def state(self, value: int): ...
    @property
    def icon_name(self) -> str: ...
    @icon_name.setter
    def icon_name(self, value: str): ...

    # GIR Methods
    def get_device(self) -> NM.DeviceEthernet: ...
    def set_device(self, value: NM.DeviceEthernet) -> None: ...
    def get_speed(self) -> int: ...
    def get_internet(self) -> int: ...
    def get_state(self) -> int: ...
    def get_icon_name(self) -> str: ...

class Network(GObject.Object):
    @staticmethod
    def get_default() -> 'Network': ...
    def __init__(self) -> None: ...
    @classmethod
    def new(cls) -> 'Network': ...

    # GIR Properties
    @property
    def client(self) -> NM.Client: ...
    @client.setter
    def client(self, value: NM.Client): ...
    @property
    def wifi(self) -> Optional[Wifi]: ...
    @wifi.setter
    def wifi(self, value: Optional[Wifi]): ...
    @property
    def wired(self) -> Optional[Wired]: ...
    @wired.setter
    def wired(self, value: Optional[Wired]): ...
    @property
    def primary(self) -> int: ...
    @primary.setter
    def primary(self, value: int): ...
    @property
    def connectivity(self) -> int: ...
    @property
    def state(self) -> int: ...

    # GIR Methods
    def get_client(self) -> NM.Client: ...
    def get_wifi(self) -> Optional[Wifi]: ...
    def get_wired(self) -> Optional[Wired]: ...
    def get_primary(self) -> int: ...
    def get_connectivity(self) -> int: ...
    def get_state(self) -> int: ...
