from typing import Any, Callable, List, Optional

from gi.repository import Gio, GLib, GObject

# Constants
MAJOR_VERSION: int = 0
MINOR_VERSION: int = 1
MICRO_VERSION: int = 0
VERSION: str = "0.1.0"

def get_default() -> 'Notifd': ...
def send_notification(
    notification: 'Notification',
    callback: Optional[Callable[[GObject.Object, Gio.AsyncResult, Any], None]] = None,
    user_data: Optional[Any] = None,
) -> None: ...
def send_notification_finish(res: Gio.AsyncResult) -> None: ...

class Urgency:
    LOW: int = 0
    NORMAL: int = 1
    CRITICAL: int = 2

class ClosedReason:
    EXPIRED: int = 1
    DISMISSED_BY_USER: int = 2
    CLOSED: int = 3
    UNDEFINED: int = 4

class State:
    DRAFT: int = 0
    SENT: int = 1
    RECEIVED: int = 2

class Action(GObject.Object):
    """Notification action."""

    @staticmethod
    def new(id: str, label: str) -> 'Action': ...

    # Properties
    @property
    def id(self) -> str: ...
    @id.setter
    def id(self, value: str) -> None: ...
    @property
    def label(self) -> str: ...
    @label.setter
    def label(self, value: str) -> None: ...

    # Methods
    def invoke(self) -> None: ...
    def get_id(self) -> str: ...
    def set_id(self, value: str) -> None: ...
    def get_label(self) -> str: ...
    def set_label(self, value: str) -> None: ...

    # Signals
    def connect(self, signal: str, callback: Callable[..., Any], *args: Any) -> int: ...
    # Signal: "invoked" -> (self)

class Notifd(GObject.Object):
    """The Notification daemon."""

    @staticmethod
    def get_default() -> 'Notifd': ...
    @staticmethod
    def new() -> 'Notifd': ...

    # Properties
    @property
    def ignore_timeout(self) -> bool: ...
    @ignore_timeout.setter
    def ignore_timeout(self, value: bool) -> None: ...
    @property
    def dont_disturb(self) -> bool: ...
    @dont_disturb.setter
    def dont_disturb(self, value: bool) -> None: ...
    @property
    def default_timeout(self) -> int: ...
    @default_timeout.setter
    def default_timeout(self, value: int) -> None: ...
    @property
    def notifications(self) -> List['Notification']: ...

    # Methods
    def get_notification(self, id: int) -> Optional['Notification']: ...
    def get_ignore_timeout(self) -> bool: ...
    def set_ignore_timeout(self, value: bool) -> None: ...
    def get_dont_disturb(self) -> bool: ...
    def set_dont_disturb(self, value: bool) -> None: ...
    def get_default_timeout(self) -> int: ...
    def set_default_timeout(self, value: int) -> None: ...
    def get_notifications(self) -> List['Notification']: ...

    # Signals
    def connect(self, signal: str, callback: Callable[..., Any], *args: Any) -> int: ...
    # Signal signatures:
    # "notified": (self, id: int, replaced: bool)
    # "resolved": (self, id: int, reason: int)

class Notification(GObject.Object):
    """Class representing a notification."""

    @staticmethod
    def new() -> 'Notification': ...

    # Properties
    @property
    def state(self) -> int: ...
    @state.setter
    def state(self, value: int) -> None: ...
    @property
    def time(self) -> int: ...
    @time.setter
    def time(self, value: int) -> None: ...
    @property
    def id(self) -> int: ...
    @id.setter
    def id(self, value: int) -> None: ...
    @property
    def app_name(self) -> str: ...
    @app_name.setter
    def app_name(self, value: str) -> None: ...
    @property
    def app_icon(self) -> str: ...
    @app_icon.setter
    def app_icon(self, value: str) -> None: ...
    @property
    def summary(self) -> str: ...
    @summary.setter
    def summary(self, value: str) -> None: ...
    @property
    def body(self) -> str: ...
    @body.setter
    def body(self, value: str) -> None: ...
    @property
    def expire_timeout(self) -> int: ...
    @expire_timeout.setter
    def expire_timeout(self, value: int) -> None: ...
    @property
    def actions(self) -> List[Action]: ...
    @property
    def hints(self) -> GLib.Variant: ...
    @hints.setter
    def hints(self, value: GLib.Variant) -> None: ...
    @property
    def image(self) -> str: ...
    @image.setter
    def image(self, value: str) -> None: ...
    @property
    def action_icons(self) -> bool: ...
    @action_icons.setter
    def action_icons(self, value: bool) -> None: ...
    @property
    def category(self) -> str: ...
    @category.setter
    def category(self, value: str) -> None: ...
    @property
    def desktop_entry(self) -> str: ...
    @desktop_entry.setter
    def desktop_entry(self, value: str) -> None: ...
    @property
    def resident(self) -> bool: ...
    @resident.setter
    def resident(self, value: bool) -> None: ...
    @property
    def sound_file(self) -> str: ...
    @sound_file.setter
    def sound_file(self, value: str) -> None: ...
    @property
    def sound_name(self) -> str: ...
    @sound_name.setter
    def sound_name(self, value: str) -> None: ...
    @property
    def suppress_sound(self) -> bool: ...
    @suppress_sound.setter
    def suppress_sound(self, value: bool) -> None: ...
    @property
    def transient(self) -> bool: ...
    @transient.setter
    def transient(self, value: bool) -> None: ...
    @property
    def x(self) -> int: ...
    @x.setter
    def x(self, value: int) -> None: ...
    @property
    def y(self) -> int: ...
    @y.setter
    def y(self, value: int) -> None: ...
    @property
    def urgency(self) -> int: ...
    @urgency.setter
    def urgency(self, value: int) -> None: ...

    # Methods
    def dismiss(self) -> None: ...
    def expire(self) -> None: ...
    def invoke(self, action_id: str) -> None: ...
    def add_action(self, action: Action) -> 'Notification': ...
    def set_hint(self, name: str, value: GLib.Variant) -> 'Notification': ...
    def get_hint(self, name: str) -> Optional[GLib.Variant]: ...
    def get_state(self) -> int: ...
    def get_time(self) -> int: ...
    def get_id(self) -> int: ...
    def set_id(self, value: int) -> None: ...
    def get_app_name(self) -> str: ...
    def set_app_name(self, value: str) -> None: ...
    def get_app_icon(self) -> str: ...
    def set_app_icon(self, value: str) -> None: ...
    def get_summary(self) -> str: ...
    def set_summary(self, value: str) -> None: ...
    def get_body(self) -> str: ...
    def set_body(self, value: str) -> None: ...
    def get_expire_timeout(self) -> int: ...
    def set_expire_timeout(self, value: int) -> None: ...
    def get_actions(self) -> List[Action]: ...
    def get_hints(self) -> GLib.Variant: ...
    def get_image(self) -> str: ...
    def set_image(self, value: str) -> None: ...
    def get_action_icons(self) -> bool: ...
    def set_action_icons(self, value: bool) -> None: ...
    def get_category(self) -> str: ...
    def set_category(self, value: str) -> None: ...
    def get_desktop_entry(self) -> str: ...
    def set_desktop_entry(self, value: str) -> None: ...
    def get_resident(self) -> bool: ...
    def set_resident(self, value: bool) -> None: ...
    def get_sound_file(self) -> str: ...
    def set_sound_file(self, value: str) -> None: ...
    def get_sound_name(self) -> str: ...
    def set_sound_name(self, value: str) -> None: ...
    def get_suppress_sound(self) -> bool: ...
    def set_suppress_sound(self, value: bool) -> None: ...
    def get_transient(self) -> bool: ...
    def set_transient(self, value: bool) -> None: ...
    def get_x(self) -> int: ...
    def set_x(self, value: int) -> None: ...
    def get_y(self) -> int: ...
    def set_y(self, value: int) -> None: ...
    def get_urgency(self) -> int: ...
    def set_urgency(self, value: int) -> None: ...

    # Signals
    def connect(self, signal: str, callback: Callable[..., Any], *args: Any) -> int: ...
    # Signal signatures:
    # "resolved": (self, reason: int)
    # "invoked": (self, action_id: str)
