from typing import List, Optional

from gi.repository import Gio, GLib, GObject

class PlaybackStatus(GObject.GEnum):
    PLAYING = 0
    PAUSED = 1
    STOPPED = 2

class Loop(GObject.GEnum):
    UNSUPPORTED = 0
    NONE = 1
    TRACK = 2
    PLAYLIST = 3

class Shuffle(GObject.GEnum):
    UNSUPPORTED = 0
    ON = 1
    OFF = 2

class Mpris(GObject.Object, Gio.ListModel):
    @staticmethod
    def get_default() -> Mpris: ...
    @staticmethod
    def new() -> Mpris: ...
    def get_players(self) -> List[Player]: ...
    @property
    def players(self) -> List[Player]: ...

class Player(GObject.Object):
    @staticmethod
    def new(name: str) -> Player: ...
    def raise_(self) -> None: ...
    def quit(self) -> None: ...
    def toggle_fullscreen(self) -> None: ...
    def next(self) -> None: ...
    def previous(self) -> None: ...
    def pause(self) -> None: ...
    def play_pause(self) -> None: ...
    def stop(self) -> None: ...
    def play(self) -> None: ...
    def open_uri(self, uri: str) -> None: ...
    def loop(self) -> None: ...
    def shuffle(self) -> None: ...
    def get_meta(self, key: str) -> Optional[GLib.Variant]: ...

    # Getters
    def get_bus_name(self) -> str: ...
    def get_available(self) -> bool: ...
    def get_can_quit(self) -> bool: ...
    def get_fullscreen(self) -> bool: ...
    def get_can_set_fullscreen(self) -> bool: ...
    def get_can_raise(self) -> bool: ...
    def get_identity(self) -> str: ...
    def get_entry(self) -> str: ...
    def get_supported_uri_schemes(self) -> List[str]: ...
    def get_supported_mime_types(self) -> List[str]: ...
    def get_loop_status(self) -> Loop: ...
    def set_loop_status(self, value: Loop) -> None: ...
    def get_shuffle_status(self) -> Shuffle: ...
    def set_shuffle_status(self, value: Shuffle) -> None: ...
    def get_rate(self) -> float: ...
    def set_rate(self, value: float) -> None: ...
    def get_volume(self) -> float: ...
    def set_volume(self, value: float) -> None: ...
    def get_position(self) -> float: ...
    def set_position(self, value: float) -> None: ...
    def get_playback_status(self) -> PlaybackStatus: ...
    def get_minimum_rate(self) -> float: ...
    def get_maximum_rate(self) -> float: ...
    def get_can_go_next(self) -> bool: ...
    def get_can_go_previous(self) -> bool: ...
    def get_can_play(self) -> bool: ...
    def get_can_pause(self) -> bool: ...
    def get_can_seek(self) -> bool: ...
    def get_can_control(self) -> bool: ...
    def get_metadata(self) -> GLib.Variant: ...
    def get_trackid(self) -> str: ...
    def get_length(self) -> float: ...
    def get_art_url(self) -> str: ...
    def get_album(self) -> str: ...
    def get_album_artist(self) -> str: ...
    def get_artist(self) -> str: ...
    def get_lyrics(self) -> str: ...
    def get_title(self) -> str: ...
    def get_composer(self) -> str: ...
    def get_comments(self) -> str: ...
    def get_cover_art(self) -> str: ...

    # Properties
    @property
    def bus_name(self) -> str: ...
    @bus_name.setter
    def bus_name(self, value: str): ...
    @property
    def available(self) -> bool: ...
    @available.setter
    def available(self, value: bool): ...
    @property
    def can_quit(self) -> bool: ...
    @can_quit.setter
    def can_quit(self, value: bool): ...
    @property
    def fullscreen(self) -> bool: ...
    @fullscreen.setter
    def fullscreen(self, value: bool): ...
    @property
    def can_set_fullscreen(self) -> bool: ...
    @can_set_fullscreen.setter
    def can_set_fullscreen(self, value: bool): ...
    @property
    def can_raise(self) -> bool: ...
    @can_raise.setter
    def can_raise(self, value: bool): ...
    @property
    def identity(self) -> str: ...
    @identity.setter
    def identity(self, value: str): ...
    @property
    def entry(self) -> str: ...
    @entry.setter
    def entry(self, value: str): ...
    @property
    def supported_uri_schemes(self) -> List[str]: ...
    @supported_uri_schemes.setter
    def supported_uri_schemes(self, value: List[str]): ...
    @property
    def supported_mime_types(self) -> List[str]: ...
    @supported_mime_types.setter
    def supported_mime_types(self, value: List[str]): ...
    @property
    def loop_status(self) -> Loop: ...
    @loop_status.setter
    def loop_status(self, value: Loop): ...
    @property
    def shuffle_status(self) -> Shuffle: ...
    @shuffle_status.setter
    def shuffle_status(self, value: Shuffle): ...
    @property
    def rate(self) -> float: ...
    @rate.setter
    def rate(self, value: float): ...
    @property
    def volume(self) -> float: ...
    @volume.setter
    def volume(self, value: float): ...
    @property
    def position(self) -> float: ...
    @position.setter
    def position(self, value: float): ...
    @property
    def playback_status(self) -> PlaybackStatus: ...
    @playback_status.setter
    def playback_status(self, value: PlaybackStatus): ...
    @property
    def minimum_rate(self) -> float: ...
    @minimum_rate.setter
    def minimum_rate(self, value: float): ...
    @property
    def maximum_rate(self) -> float: ...
    @maximum_rate.setter
    def maximum_rate(self, value: float): ...
    @property
    def can_go_next(self) -> bool: ...
    @can_go_next.setter
    def can_go_next(self, value: bool): ...
    @property
    def can_go_previous(self) -> bool: ...
    @can_go_previous.setter
    def can_go_previous(self, value: bool): ...
    @property
    def can_play(self) -> bool: ...
    @can_play.setter
    def can_play(self, value: bool): ...
    @property
    def can_pause(self) -> bool: ...
    @can_pause.setter
    def can_pause(self, value: bool): ...
    @property
    def can_seek(self) -> bool: ...
    @can_seek.setter
    def can_seek(self, value: bool): ...
    @property
    def can_control(self) -> bool: ...
    @can_control.setter
    def can_control(self, value: bool): ...
    @property
    def metadata(self) -> GLib.Variant: ...
    @metadata.setter
    def metadata(self, value: GLib.Variant): ...
    @property
    def trackid(self) -> str: ...
    @trackid.setter
    def trackid(self, value: str): ...
    @property
    def length(self) -> float: ...
    @length.setter
    def length(self, value: float): ...
    @property
    def art_url(self) -> str: ...
    @art_url.setter
    def art_url(self, value: str): ...
    @property
    def album(self) -> str: ...
    @album.setter
    def album(self, value: str): ...
    @property
    def album_artist(self) -> str: ...
    @album_artist.setter
    def album_artist(self, value: str): ...
    @property
    def artist(self) -> str: ...
    @artist.setter
    def artist(self, value: str): ...
    @property
    def lyrics(self) -> str: ...
    @lyrics.setter
    def lyrics(self, value: str): ...
    @property
    def title(self) -> str: ...
    @title.setter
    def title(self, value: str): ...
    @property
    def composer(self) -> str: ...
    @composer.setter
    def composer(self, value: str): ...
    @property
    def comments(self) -> str: ...
    @comments.setter
    def comments(self, value: str): ...
    @property
    def cover_art(self) -> str: ...
    @cover_art.setter
    def cover_art(self, value: str): ...

MAJOR_VERSION: int = ...
MINOR_VERSION: int = ...
MICRO_VERSION: int = ...
VERSION: str = ...

def get_default() -> Mpris: ...
