from typing import Any, Callable, List, Optional
from gi.repository import Gio, GObject, GLib

# Constants
MAJOR_VERSION: int = 0
MINOR_VERSION: int = 1
MICRO_VERSION: int = 0
VERSION: str = "0.1.0"

def get_default() -> 'Wp': ...

class Available:
    UNKNOWN: int = 0
    NO: int = 1
    YES: int = 2

class DeviceType:
    UNKNOWN: int = 0
    AUDIO_DEVICE: int = 1
    VIDEO_DEVICE: int = 2

    @staticmethod
    def from_string(string: str) -> int: ...
    @staticmethod
    def to_string(device_type: int) -> str: ...

class Direction:
    INPUT: int = 0
    OUTPUT: int = 1

class MediaCategory:
    UNKNOWN: int = 0
    PLAYBACK: int = 1
    CAPTURE: int = 2
    DUPLEX: int = 3
    MONITOR: int = 4
    MANAGER: int = 5

    @staticmethod
    def from_string(string: str) -> int: ...
    @staticmethod
    def to_string(category: int) -> str: ...

class MediaClass:
    UNKNOWN: int = 0
    AUDIO_SOURCE: int = 1
    AUDIO_SINK: int = 2
    STREAM_INPUT_AUDIO: int = 3
    STREAM_OUTPUT_AUDIO: int = 4
    VIDEO_SOURCE: int = 5
    VIDEO_SINK: int = 6
    STREAM_INPUT_VIDEO: int = 7
    STREAM_OUTPUT_VIDEO: int = 8

    @staticmethod
    def from_string(string: str) -> int: ...
    @staticmethod
    def to_string(media_class: int) -> str: ...

class MediaRole:
    UNKNOWN: int = 0
    MOVIE: int = 1
    MUSIC: int = 2
    CAMERA: int = 3
    SCREEN: int = 4
    COMMUNICATION: int = 5
    GAME: int = 6
    NOTIFICATION: int = 7
    DSP: int = 8
    PRODUCTION: int = 9
    ACCESSIBILITY: int = 10
    TEST: int = 11

    @staticmethod
    def from_string(string: str) -> int: ...
    @staticmethod
    def to_string(role: int) -> str: ...

class NodeState:
    ERROR: int = -1
    CREATING: int = 0
    SUSPENDED: int = 1
    IDLE: int = 2
    RUNNING: int = 3

class Scale:
    LINEAR: int = 0
    CUBIC: int = 1

class Channel(GObject.Object):
    @property
    def name(self) -> str: ...
    @property
    def volume(self) -> float: ...
    @volume.setter
    def volume(self, value: float) -> None: ...
    @property
    def volume_icon(self) -> str: ...

    def get_name(self) -> str: ...
    def get_volume(self) -> float: ...
    def get_volume_icon(self) -> str: ...
    def set_volume(self, volume: float) -> None: ...

class Node(GObject.Object):
    @property
    def channels(self) -> List[Channel]: ...
    @property
    def description(self) -> str: ...
    @property
    def icon(self) -> str: ...
    @property
    def id(self) -> int: ...
    @property
    def lock_channels(self) -> bool: ...
    @lock_channels.setter
    def lock_channels(self, value: bool) -> None: ...
    @property
    def media_class(self) -> int: ...
    @property
    def mute(self) -> bool: ...
    @mute.setter
    def mute(self, value: bool) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def path(self) -> str: ...
    @property
    def serial(self) -> int: ...
    @property
    def state(self) -> int: ...
    @property
    def volume(self) -> float: ...
    @volume.setter
    def volume(self, value: float) -> None: ...
    @property
    def volume_icon(self) -> str: ...

    def get_channels(self) -> List[Channel]: ...
    def get_description(self) -> str: ...
    def get_icon(self) -> str: ...
    def get_id(self) -> int: ...
    def get_lock_channels(self) -> bool: ...
    def get_media_class(self) -> int: ...
    def get_mute(self) -> bool: ...
    def get_name(self) -> str: ...
    def get_path(self) -> str: ...
    def get_pw_property(self, key: str) -> Optional[str]: ...
    def get_serial(self) -> int: ...
    def get_state(self) -> int: ...
    def get_volume(self) -> float: ...
    def get_volume_icon(self) -> str: ...
    def set_lock_channels(self, lock_channels: bool) -> None: ...
    def set_mute(self, mute: bool) -> None: ...
    def set_volume(self, volume: float) -> None: ...

    # Virtual Methods / Signals
    def do_metadata_changed(self, key: str, type: str, value: str) -> None: ...
    def do_params_changed(self, id: str) -> None: ...

class Route(GObject.Object):
    @property
    def available(self) -> int: ...
    @property
    def description(self) -> str: ...
    @property
    def direction(self) -> int: ...
    @property
    def index(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def priority(self) -> int: ...

    def get_available(self) -> int: ...
    def get_description(self) -> str: ...
    def get_device(self) -> int: ...
    def get_direction(self) -> int: ...
    def get_index(self) -> int: ...
    def get_name(self) -> str: ...
    def get_priority(self) -> int: ...

class Profile(GObject.Object):
    @property
    def available(self) -> int: ...
    @property
    def description(self) -> str: ...
    @property
    def index(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def priority(self) -> int: ...

    def get_available(self) -> int: ...
    def get_description(self) -> str: ...
    def get_index(self) -> int: ...
    def get_name(self) -> str: ...
    def get_priority(self) -> int: ...

class Device(GObject.Object):
    @property
    def active_profile_id(self) -> int: ...
    @active_profile_id.setter
    def active_profile_id(self, value: int) -> None: ...
    @property
    def description(self) -> str: ...
    @property
    def device_type(self) -> int: ...
    @property
    def form_factor(self) -> str: ...
    @property
    def icon(self) -> str: ...
    @property
    def id(self) -> int: ...
    @property
    def input_route_id(self) -> int: ...
    @input_route_id.setter
    def input_route_id(self, value: int) -> None: ...
    @property
    def input_routes(self) -> List[Route]: ...
    @property
    def output_route_id(self) -> int: ...
    @output_route_id.setter
    def output_route_id(self, value: int) -> None: ...
    @property
    def output_routes(self) -> List[Route]: ...
    @property
    def profiles(self) -> List[Profile]: ...
    @property
    def routes(self) -> List[Route]: ...

    def get_active_profile_id(self) -> int: ...
    def get_description(self) -> str: ...
    def get_device_type(self) -> int: ...
    def get_form_factor(self) -> str: ...
    def get_icon(self) -> str: ...
    def get_id(self) -> int: ...
    def get_input_route_id(self) -> int: ...
    def get_input_routes(self) -> List[Route]: ...
    def get_output_route_id(self) -> int: ...
    def get_output_routes(self) -> List[Route]: ...
    def get_profile(self, id: int) -> Optional[Profile]: ...
    def get_profiles(self) -> List[Profile]: ...
    def get_pw_property(self, key: str) -> Optional[str]: ...
    def get_route(self, id: int) -> Optional[Route]: ...
    def get_routes(self) -> List[Route]: ...
    def set_active_profile_id(self, profile_id: int) -> None: ...
    def set_route(self, route: Route, card_device: int) -> None: ...

class Endpoint(Node):
    @property
    def device(self) -> Optional[Device]: ...
    @property
    def device_id(self) -> int: ...
    @property
    def is_default(self) -> bool: ...
    @is_default.setter
    def is_default(self, value: bool) -> None: ...
    @property
    def route(self) -> Optional[Route]: ...
    @route.setter
    def route(self, value: Route) -> None: ...
    @property
    def route_id(self) -> int: ...
    @route_id.setter
    def route_id(self, value: int) -> None: ...
    @property
    def routes(self) -> List[Route]: ...

    def get_device(self) -> Optional[Device]: ...
    def get_device_id(self) -> int: ...
    def get_is_default(self) -> bool: ...
    def get_route(self) -> Optional[Route]: ...
    def get_route_id(self) -> int: ...
    def get_routes(self) -> List[Route]: ...
    def set_is_default(self, is_default: bool) -> None: ...
    def set_route(self, route: Route) -> None: ...
    def set_route_id(self, route_id: int) -> None: ...

class Stream(Node):
    @property
    def media_category(self) -> int: ...
    @property
    def media_role(self) -> int: ...
    @property
    def target_endpoint(self) -> Optional[Endpoint]: ...
    @target_endpoint.setter
    def target_endpoint(self, value: Optional[Endpoint]) -> None: ...
    @property
    def target_serial(self) -> int: ...
    @target_serial.setter
    def target_serial(self, value: int) -> None: ...

    def get_media_category(self) -> int: ...
    def get_media_role(self) -> int: ...
    def get_target_endpoint(self) -> Optional[Endpoint]: ...
    def get_target_serial(self) -> int: ...
    def set_target_endpoint(self, target: Optional[Endpoint]) -> None: ...
    def set_target_serial(self, serial: int) -> None: ...

class Audio(GObject.Object):
    @staticmethod
    def new(wp: 'Wp') -> 'Audio': ...

    @property
    def default_microphone(self) -> Endpoint: ...
    @property
    def default_speaker(self) -> Endpoint: ...
    @property
    def devices(self) -> List[Device]: ...
    @property
    def microphones(self) -> List[Endpoint]: ...
    @property
    def recorders(self) -> List[Stream]: ...
    @property
    def speakers(self) -> List[Endpoint]: ...
    @property
    def streams(self) -> List[Stream]: ...

    def get_default_microphone(self) -> Endpoint: ...
    def get_default_speaker(self) -> Endpoint: ...
    def get_device(self, id: int) -> Optional[Device]: ...
    def get_devices(self) -> List[Device]: ...
    def get_microphone(self, id: int) -> Optional[Endpoint]: ...
    def get_microphones(self) -> List[Endpoint]: ...
    def get_node(self, id: int) -> Optional[Node]: ...
    def get_recorder(self, id: int) -> Optional[Stream]: ...
    def get_recorders(self) -> List[Stream]: ...
    def get_speaker(self, id: int) -> Optional[Endpoint]: ...
    def get_speakers(self) -> List[Endpoint]: ...
    def get_stream(self, id: int) -> Optional[Stream]: ...
    def get_streams(self) -> List[Stream]: ...

    # Signals
    def connect(self, signal: str, callback: Callable[..., Any]) -> int: ...
    # Signals: device-added, device-removed, microphone-added, microphone-removed, 
    # recorder-added, recorder-removed, speaker-added, speaker-removed, 
    # stream-added, stream-removed

class Video(GObject.Object):
    @staticmethod
    def new(wp: 'Wp') -> 'Video': ...

    @property
    def devices(self) -> List[Device]: ...
    @property
    def recorders(self) -> List[Stream]: ...
    @property
    def sinks(self) -> List[Endpoint]: ...
    @property
    def sources(self) -> List[Endpoint]: ...
    @property
    def streams(self) -> List[Stream]: ...

    def get_device(self, id: int) -> Optional[Device]: ...
    def get_devices(self) -> List[Device]: ...
    def get_recorder(self, id: int) -> Optional[Stream]: ...
    def get_recorders(self) -> List[Stream]: ...
    def get_sink(self, id: int) -> Optional[Endpoint]: ...
    def get_sinks(self) -> List[Endpoint]: ...
    def get_source(self, id: int) -> Optional[Endpoint]: ...
    def get_sources(self) -> List[Endpoint]: ...
    def get_stream(self, id: int) -> Optional[Stream]: ...
    def get_streams(self) -> List[Stream]: ...

    # Signals
    def connect(self, signal: str, callback: Callable[..., Any]) -> int: ...
    # Signals: device-added, device-removed, recorder-added, recorder-removed, 
    # sink-added, sink-removed, source-added, source-removed, 
    # stream-added, stream-removed

class Wp(GObject.Object):
    @staticmethod
    def get_default() -> 'Wp': ...
    @staticmethod
    def new() -> 'Wp': ...

    @property
    def audio(self) -> Audio: ...
    @property
    def connected(self) -> bool: ...
    @property
    def default_microphone(self) -> Endpoint: ...
    @property
    def default_speaker(self) -> Endpoint: ...
    @property
    def devices(self) -> List[Device]: ...
    @property
    def nodes(self) -> List[Node]: ...
    @property
    def scale(self) -> int: ...
    @scale.setter
    def scale(self, value: int) -> None: ...
    @property
    def video(self) -> Video: ...

    def get_audio(self) -> Audio: ...
    def get_default_microphone(self) -> Endpoint: ...
    def get_default_speaker(self) -> Endpoint: ...
    def get_device(self, id: int) -> Optional[Device]: ...
    def get_devices(self) -> List[Device]: ...
    def get_node(self, id: int) -> Optional[Node]: ...
    def get_node_by_serial(self, serial: int) -> Optional[Node]: ...
    def get_nodes(self) -> List[Node]: ...
    def get_scale(self) -> int: ...
    def get_video(self) -> Video: ...
    def set_scale(self, scale: int) -> None: ...

    # Signals
    def connect(self, signal: str, callback: Callable[..., Any]) -> int: ...
    # Signals: device-added, device-removed, node-added, node-removed, ready
