# Stubs generated from Astal-3.0.gir
import enum
from typing import Any, Callable, List, Optional

from gi.repository import AstalIO  # From <include name="AstalIO" version="0.1" />
from gi.repository import Gdk, GdkPixbuf, Gio, GLib, GObject, Gtk

# --- Enums & Bitfields ---

class MouseButton(enum.IntEnum):
    PRIMARY = 1
    MIDDLE = 2
    SECONDARY = 3
    BACK = 4
    FORWARD = 5

class WindowAnchor(enum.IntFlag):
    NONE = 1
    TOP = 2
    RIGHT = 4
    LEFT = 8
    BOTTOM = 16

class Exclusivity(enum.IntEnum):
    NORMAL = 0
    EXCLUSIVE = 1
    IGNORE = 2

class Layer(enum.IntEnum):
    BACKGROUND = 0
    BOTTOM = 1
    TOP = 2
    OVERLAY = 3

class Keymode(enum.IntEnum):
    NONE = 0
    EXCLUSIVE = 1
    ON_DEMAND = 2

# --- Records (for Event Structs) ---

class ClickEvent:
    release: bool
    time: int
    x: float
    y: float
    modifier: Gdk.ModifierType
    button: MouseButton
    def init(self, event: Gdk.EventButton) -> None: ...

class HoverEvent:
    lost: bool
    time: int
    x: float
    y: float
    modifier: Gdk.ModifierType
    mode: Gdk.CrossingMode
    detail: Gdk.NotifyType
    def init(self, event: Gdk.EventCrossing) -> None: ...

class ScrollEvent:
    time: int
    x: float
    y: float
    modifier: Gdk.ModifierType
    direction: Gdk.ScrollDirection
    delta_x: float
    delta_y: float
    def init(self, event: Gdk.EventScroll) -> None: ...

class MotionEvent:
    time: int
    x: float
    y: float
    modifier: Gdk.ModifierType
    def init(self, event: Gdk.EventMotion) -> None: ...

# --- Classes ---

class Box(Gtk.Box):
    # Properties
    vertical: GObject.Property[bool, Any]
    children: GObject.Property[GLib.List[Gtk.Widget], Any]
    child: GObject.Property[Gtk.Widget, Any]

    # Constructor
    def new(self, vertical: bool, children: GLib.List[Gtk.Widget]) -> Box: ...

    # Methods
    def get_vertical(self) -> bool: ...
    def set_vertical(self, value: bool) -> None: ...
    def get_children(self) -> GLib.List[Gtk.Widget]: ...
    def set_children(self, value: GLib.List[Gtk.Widget]) -> None: ...
    def get_child(self) -> Gtk.Widget: ...
    def set_child(self, value: Gtk.Widget) -> None: ...

class Button(Gtk.Button):
    # Constructor
    def new() -> Button: ...

    # Signals
    def connect(self, signal: str, callback: Callable, *args: Any) -> int:
        if signal == "hover":
            ...  # callback(self, event: HoverEvent)
        elif signal == "hover-lost":
            ...  # callback(self, event: HoverEvent)
        elif signal == "click":
            ...  # callback(self, event: ClickEvent)
        elif signal == "click-release":
            ...  # callback(self, event: ClickEvent)
        elif signal == "scroll":
            ...  # callback(self, event: ScrollEvent)
        else:
            super().connect(signal, callback, *args)

class CenterBox(Gtk.Box):
    # Properties
    vertical: GObject.Property[bool, Any]
    start_widget: GObject.Property[Gtk.Widget, Any]
    end_widget: GObject.Property[Gtk.Widget, Any]
    center_widget: GObject.Property[Gtk.Widget, Any]

    # Constructor
    def new() -> CenterBox: ...

    # Methods
    def get_vertical(self) -> bool: ...
    def set_vertical(self, value: bool) -> None: ...
    def get_start_widget(self) -> Gtk.Widget: ...
    def set_start_widget(self, value: Gtk.Widget) -> None: ...
    def get_end_widget(self) -> Gtk.Widget: ...
    def set_end_widget(self, value: Gtk.Widget) -> None: ...
    def get_center_widget(self) -> Gtk.Widget: ...
    def set_center_widget(self, value: Gtk.Widget) -> None: ...

class CircularProgress(Gtk.Bin):
    # Properties
    start_at: GObject.Property[float, Any]
    end_at: GObject.Property[float, Any]
    value: GObject.Property[float, Any]
    inverted: GObject.Property[bool, Any]
    rounded: GObject.Property[bool, Any]

    # Constructor
    def new() -> CircularProgress: ...

    # Methods
    def get_start_at(self) -> float: ...
    def set_start_at(self, value: float) -> None: ...
    def get_end_at(self) -> float: ...
    def set_end_at(self, value: float) -> None: ...
    def get_value(self) -> float: ...
    def set_value(self, value: float) -> None: ...
    def get_inverted(self) -> bool: ...
    def set_inverted(self, value: bool) -> None: ...
    def get_rounded(self) -> bool: ...
    def set_rounded(self, value: bool) -> None: ...

class EventBox(Gtk.EventBox):
    # Constructor
    def new() -> EventBox: ...

    # Signals
    def connect(self, signal: str, callback: Callable, *args: Any) -> int:
        if signal == "hover":
            ...  # callback(self, event: HoverEvent)
        elif signal == "hover-lost":
            ...  # callback(self, event: HoverEvent)
        elif signal == "click":
            ...  # callback(self, event: ClickEvent)
        elif signal == "click-release":
            ...  # callback(self, event: ClickEvent)
        elif signal == "scroll":
            ...  # callback(self, event: ScrollEvent)
        elif signal == "motion":
            ...  # callback(self, event: MotionEvent)
        else:
            super().connect(signal, callback, *args)

class Icon(Gtk.Image):
    # Properties
    pixbuf: GObject.Property[GdkPixbuf.Pixbuf, Any]
    g_icon: GObject.Property[Gio.Icon, Any]
    icon: GObject.Property[str, Any]

    # Static Methods
    @staticmethod
    def lookup_icon(icon: str) -> Optional[Gtk.IconInfo]: ...

    # Constructor
    def new() -> Icon: ...

    # Methods
    def get_pixbuf(self) -> GdkPixbuf.Pixbuf: ...
    def set_pixbuf(self, value: GdkPixbuf.Pixbuf) -> None: ...
    def get_g_icon(self) -> Gio.Icon: ...
    def set_g_icon(self, value: Gio.Icon) -> None: ...
    def get_icon(self) -> str: ...
    def set_icon(self, value: str) -> None: ...

class Label(Gtk.Label):
    # Properties
    truncate: GObject.Property[bool, Any]
    justify_fill: GObject.Property[bool, Any]

    # Constructor
    def new() -> Label: ...

    # Methods
    def get_truncate(self) -> bool: ...
    def set_truncate(self, value: bool) -> None: ...
    def get_justify_fill(self) -> bool: ...
    def set_justify_fill(self, value: bool) -> None: ...

class LevelBar(Gtk.LevelBar):
    # Properties
    vertical: GObject.Property[bool, Any]

    # Constructor
    def new() -> LevelBar: ...

    # Methods
    def get_vertical(self) -> bool: ...
    def set_vertical(self, value: bool) -> None: ...

class Overlay(Gtk.Overlay):
    # Properties
    pass_through: GObject.Property[bool, Any]
    overlay: GObject.Property[Optional[Gtk.Widget], Any]
    overlays: GObject.Property[GLib.List[Gtk.Widget], Any]
    child: GObject.Property[Optional[Gtk.Widget], Any]

    # Constructor
    def new() -> Overlay: ...

    # Methods
    def add_overlay(self, widget: Gtk.Widget) -> None: ...
    def get_pass_through(self) -> bool: ...
    def set_pass_through(self, value: bool) -> None: ...
    def get_overlay(self) -> Optional[Gtk.Widget]: ...
    def set_overlay(self, value: Optional[Gtk.Widget]) -> None: ...
    def get_overlays(self) -> GLib.List[Gtk.Widget]: ...
    def set_overlays(self, value: GLib.List[Gtk.Widget]) -> None: ...
    def get_child(self) -> Optional[Gtk.Widget]: ...
    def set_child(self, value: Optional[Gtk.Widget]) -> None: ...

class Scrollable(Gtk.ScrolledWindow):
    # Properties
    hscroll: GObject.Property[Gtk.PolicyType, Any]
    vscroll: GObject.Property[Gtk.PolicyType, Any]

    # Constructor
    def new() -> Scrollable: ...

    # Methods
    def get_child(self) -> Gtk.Widget: ...
    def get_hscroll(self) -> Gtk.PolicyType: ...
    def set_hscroll(self, value: Gtk.PolicyType) -> None: ...
    def get_vscroll(self) -> Gtk.PolicyType: ...
    def set_vscroll(self, value: Gtk.PolicyType) -> None: ...

class Slider(Gtk.Scale):
    # Properties
    vertical: GObject.Property[bool, Any]
    dragging: GObject.Property[bool, Any]
    value: GObject.Property[float, Any]
    min: GObject.Property[float, Any]
    max: GObject.Property[float, Any]
    step: GObject.Property[float, Any]
    page: GObject.Property[float, Any]

    # Constructor
    def new() -> Slider: ...

    # Methods
    def get_vertical(self) -> bool: ...
    def set_vertical(self, value: bool) -> None: ...
    def get_dragging(self) -> bool: ...
    def get_value(self) -> float: ...
    def set_value(self, value: float) -> None: ...
    def get_min(self) -> float: ...
    def set_min(self, value: float) -> None: ...
    def get_max(self) -> float: ...
    def set_max(self, value: float) -> None: ...
    def get_step(self) -> float: ...
    def set_step(self, value: float) -> None: ...
    def get_page(self) -> float: ...
    def set_page(self, value: float) -> None: ...

    # Signals
    def connect(self, signal: str, callback: Callable, *args: Any) -> int:
        if signal == "dragged":
            ...  # callback(self)
        else:
            super().connect(signal, callback, *args)

class Stack(Gtk.Stack):
    # Properties
    shown: GObject.Property[str, Any]
    children: GObject.Property[GLib.List[Gtk.Widget], Any]

    # Constructor
    def new() -> Stack: ...

    # Methods
    def get_shown(self) -> str: ...
    def set_shown(self, value: str) -> None: ...
    def get_children(self) -> GLib.List[Gtk.Widget]: ...
    def set_children(self, value: GLib.List[Gtk.Widget]) -> None: ...

class Window(Gtk.Window):
    # Properties
    inhibit: GObject.Property[bool, Any]
    namespace: GObject.Property[str, Any]
    anchor: GObject.Property[WindowAnchor, Any]
    exclusivity: GObject.Property[Exclusivity, Any]
    layer: GObject.Property[Layer, Any]
    keymode: GObject.Property[Keymode, Any]
    gdkmonitor: GObject.Property[Gdk.Monitor, Any]
    margin_top: GObject.Property[int, Any]
    margin_bottom: GObject.Property[int, Any]
    margin_left: GObject.Property[int, Any]
    margin_right: GObject.Property[int, Any]
    margin: GObject.Property[int, Any]
    monitor: GObject.Property[int, Any]

    # Constructor
    def new() -> Window: ...

    # Methods
    def get_current_monitor(self) -> Gdk.Monitor: ...
    def get_inhibit(self) -> bool: ...
    def set_inhibit(self, value: bool) -> None: ...
    def get_namespace(self) -> str: ...
    def set_namespace(self, value: str) -> None: ...
    def get_anchor(self) -> WindowAnchor: ...
    def set_anchor(self, value: WindowAnchor) -> None: ...
    def get_exclusivity(self) -> Exclusivity: ...
    def set_exclusivity(self, value: Exclusivity) -> None: ...
    def get_layer(self) -> Layer: ...
    def set_layer(self, value: Layer) -> None: ...
    def get_keymode(self) -> Keymode: ...
    def set_keymode(self, value: Keymode) -> None: ...
    def get_gdkmonitor(self) -> Gdk.Monitor: ...
    def set_gdkmonitor(self, value: Gdk.Monitor) -> None: ...
    def get_margin_top(self) -> int: ...
    def set_margin_top(self, value: int) -> None: ...
    def get_margin_bottom(self) -> int: ...
    def set_margin_bottom(self, value: int) -> None: ...
    def get_margin_left(self) -> int: ...
    def set_margin_left(self, value: int) -> None: ...
    def get_margin_right(self) -> int: ...
    def set_margin_right(self, value: int) -> None: ...
    def set_margin(self, value: int) -> None: ...
    def get_monitor(self) -> int: ...
    def set_monitor(self, value: int) -> None: ...

class Application(Gtk.Application, AstalIO.Application):
    # Properties
    monitors: GObject.Property[GLib.List[Gdk.Monitor], Any]
    windows: GObject.Property[GLib.List[Gtk.Window], Any]
    gtk_theme: GObject.Property[str, Any]
    icon_theme: GObject.Property[str, Any]
    cursor_theme: GObject.Property[str, Any]

    # Constructor
    def new() -> Application: ...

    # Methods
    def reset_css(self) -> None: ...
    def get_window(self, name: str) -> Optional[Gtk.Window]: ...
    def apply_css(self, style: str, reset: bool) -> None: ...
    def add_icons(self, path: Optional[str]) -> None: ...
    def request(self, request: str, conn: Gio.SocketConnection) -> None: ...
    def get_monitors(self) -> GLib.List[Gdk.Monitor]: ...
    def get_windows(self) -> GLib.List[Gtk.Window]: ...
    def get_gtk_theme(self) -> str: ...
    def set_gtk_theme(self, value: str) -> None: ...
    def get_icon_theme(self) -> str: ...
    def set_icon_theme(self, value: str) -> None: ...
    def get_cursor_theme(self) -> str: ...
    def set_cursor_theme(self, value: str) -> None: ...

    # Signals
    def connect(self, signal: str, callback: Callable, *args: Any) -> int:
        if signal == "monitor-added":
            ...  # callback(self, monitor: Gdk.Monitor)
        elif signal == "monitor-removed":
            ...  # callback(self, monitor: Gdk.Monitor)
        elif signal == "window-toggled":
            ...  # callback(self, window: Gtk.Window)
        else:
            super().connect(signal, callback, *args)

# --- Top-level Constants ---

MAJOR_VERSION: int
MINOR_VERSION: int
MICRO_VERSION: int
VERSION: str

# --- Top-level Functions ---

def widget_set_css(widget: Gtk.Widget, css: str) -> None: ...
def widget_get_css(widget: Gtk.Widget) -> str: ...
def widget_set_class_names(widget: Gtk.Widget, class_names: List[str]) -> None: ...
def widget_get_class_names(widget: Gtk.Widget) -> GLib.List[str]: ...
def widget_toggle_class_name(
    widget: Gtk.Widget, class_name: str, condition: bool
) -> None: ...
def widget_set_cursor(widget: Gtk.Widget, cursor: str) -> None: ...
def widget_get_cursor(widget: Gtk.Widget) -> str: ...
def widget_set_click_through(widget: Gtk.Widget, click_through: bool) -> None: ...
def widget_get_click_through(widget: Gg.Widget) -> bool: ...
