from typing import Any, Callable, List, Optional

from gi.repository import GdkPixbuf, Gio, GLib, GObject

# Constants
MAJOR_VERSION: int = 0
MINOR_VERSION: int = 1
MICRO_VERSION: int = 0
VERSION: str = "0.1.0"

def get_default() -> 'Tray': ...

class Category:
    APPLICATION: int = 0
    COMMUNICATIONS: int = 1
    SYSTEM: int = 2
    HARDWARE: int = 3

def category_to_nick(self: int) -> str: ...
def category_from_string(value: str) -> int: ...

class Status:
    PASSIVE: int = 0
    ACTIVE: int = 1
    NEEDS_ATTENTION: int = 2

def status_to_nick(self: int) -> str: ...
def status_from_string(value: str) -> int: ...

class Pixmap:
    width: int
    height: int
    bytes: bytes

class Tooltip:
    icon_name: str
    icon: List[Pixmap]
    title: str
    description: str

class TrayItem(GObject.Object):
    # Properties
    @property
    def title(self) -> str: ...
    @property
    def category(self) -> int: ...
    @property
    def status(self) -> int: ...
    @property
    def tooltip(self) -> Optional[Tooltip]: ...
    @property
    def tooltip_markup(self) -> str: ...
    @property
    def tooltip_text(self) -> str: ...
    @property
    def id(self) -> str: ...
    @property
    def is_menu(self) -> bool: ...
    @property
    def icon_theme_path(self) -> str: ...
    @property
    def icon_name(self) -> str: ...
    @property
    def icon_pixbuf(self) -> GdkPixbuf.Pixbuf: ...
    @property
    def gicon(self) -> Gio.Icon: ...
    @property
    def item_id(self) -> str: ...
    @property
    def menu_path(self) -> str: ...
    @property
    def menu_model(self) -> Optional[Gio.MenuModel]: ...
    @property
    def action_group(self) -> Optional[Gio.ActionGroup]: ...

    # Methods
    def about_to_show(self) -> None: ...
    def activate(self, x: int, y: int) -> None: ...
    def secondary_activate(self, x: int, y: int) -> None: ...
    def scroll(self, delta: int, orientation: str) -> None: ...
    def to_json_string(self) -> str: ...
    def get_title(self) -> str: ...
    def get_category(self) -> int: ...
    def get_status(self) -> int: ...
    def get_tooltip(self) -> Optional[Tooltip]: ...
    def get_tooltip_markup(self) -> str: ...
    def get_tooltip_text(self) -> str: ...
    def get_id(self) -> str: ...
    def get_is_menu(self) -> bool: ...
    def get_icon_theme_path(self) -> str: ...
    def get_icon_name(self) -> str: ...
    def get_icon_pixbuf(self) -> GdkPixbuf.Pixbuf: ...
    def get_gicon(self) -> Gio.Icon: ...
    def get_item_id(self) -> str: ...
    def get_menu_path(self) -> str: ...
    def get_menu_model(self) -> Optional[Gio.MenuModel]: ...
    def get_action_group(self) -> Optional[Gio.ActionGroup]: ...

    # Signals
    def connect(self, signal: str, callback: Callable[..., Any]) -> int: ...
    # Signals: "changed", "ready"

class Tray(GObject.Object):
    @staticmethod
    def get_default() -> 'Tray': ...
    @staticmethod
    def new() -> 'Tray': ...
    @property
    def items(self) -> List[TrayItem]: ...
    @property
    def items_model(self) -> Gio.ListModel: ...
    def get_item(self, item_id: str) -> TrayItem: ...
    def get_items(self) -> List[TrayItem]: ...
    def get_items_model(self) -> Gio.ListModel: ...
    def connect(self, signal: str, callback: Callable[..., Any]) -> int: ...
    # Signals: "item-added" (id), "item-removed" (id)
