# Stubs generated from AstalApps-0.1.gir
from typing import Any, Callable, List, Optional, Tuple

from gi.repository import GLib, GObject

class Score:
    """
    Stub for record AstalApps.Score
    """

    name: int
    entry: int
    executable: int
    description: int
    keywords: int
    categories: int

class Application(GObject.Object):
    """
    Object representing an applications .desktop file.
    """

    # Properties
    app: GObject.Property[GLib.DesktopAppInfo, Any]
    frequency: GObject.Property[int, Any]
    name: GObject.Property[str, Any]
    entry: GObject.Property[str, Any]
    description: GObject.Property[str, Any]
    wm_class: GObject.Property[str, Any]
    executable: GObject.Property[str, Any]
    icon_name: GObject.Property[str, Any]
    keywords: GObject.Property[Any, Any]  # Array
    categories: GObject.Property[Any, Any]  # Array

    # Methods
    def get_key(self, key: str) -> str: ...
    def launch(self) -> bool: ...
    def fuzzy_match(self, term: str) -> Score: ...
    def exact_match(self, term: str) -> Score: ...
    def get_app(self) -> GLib.DesktopAppInfo: ...
    def set_app(self, value: GLib.DesktopAppInfo) -> None: ...
    def get_frequency(self) -> int: ...
    def set_frequency(self, value: int) -> None: ...
    def get_name(self) -> str: ...
    def get_entry(self) -> str: ...
    def get_description(self) -> str: ...
    def get_wm_class(self) -> str: ...
    def get_executable(self) -> str: ...
    def get_icon_name(self) -> str: ...
    def get_keywords(self) -> Tuple[List[str], int]: ...
    def get_categories(self) -> Tuple[List[str], int]: ...

class Apps(GObject.Object):
    """
    This object can be used to query applications.
    """

    # Properties
    show_hidden: GObject.Property[bool, Any]
    list: GObject.Property[GLib.List[Application], Any]
    min_score: GObject.Property[float, Any]
    name_multiplier: GObject.Property[float, Any]
    entry_multiplier: GObject.Property[float, Any]
    executable_multiplier: GObject.Property[float, Any]
    description_multiplier: GObject.Property[float, Any]
    keywords_multiplier: GObject.Property[float, Any]
    categories_multiplier: GObject.Property[float, Any]

    # Constructor
    def new(self) -> Apps: ...

    # Methods
    def fuzzy_score(self, search: str, a: Application) -> float: ...
    def exact_score(self, search: str, a: Application) -> float: ...
    def fuzzy_query(self, search: Optional[str]) -> GLib.List[Application]: ...
    def exact_query(self, search: Optional[str]) -> GLib.List[Application]: ...
    def reload(self) -> None: ...
    def get_show_hidden(self) -> bool: ...
    def set_show_hidden(self, value: bool) -> None: ...
    def get_list(self) -> GLib.List[Application]: ...
    def get_min_score(self) -> float: ...
    def set_min_score(self, value: float) -> None: ...
    def get_name_multiplier(self) -> float: ...
    def set_name_multiplier(self, value: float) -> None: ...
    def get_entry_multiplier(self) -> float: ...
    def set_entry_multiplier(self, value: float) -> None: ...
    def get_executable_multiplier(self) -> float: ...
    def set_executable_multiplier(self, value: float) -> None: ...
    def get_description_multiplier(self) -> float: ...
    def set_description_multiplier(self, value: float) -> None: ...
    def get_keywords_multiplier(self) -> float: ...
    def set_keywords_multiplier(self, value: float) -> None: ...
    def get_categories_multiplier(self) -> float: ...
    def set_categories_multiplier(self, value: float) -> None: ...

# --- Top-level Constants ---

MAJOR_VERSION: int
MINOR_VERSION: int
MICRO_VERSION: int
VERSION: str
